# Effect

<aside>
💡 Effect는 개발자가 복잡한 동기식 및 비동기식 프로그램을 쉽게 만들 수 있도록 설계된 강력한 TypeScript 라이브러리입니다.

</aside>

## Effect가 필요한 이유

 타입스크립트는 자바스크립트 코드를 정적 타이핑하는데 매우 효과적이지만 몇 가지 단점이 발생할 수 있다.

- 비동기 코드의 복잡한 특성 관리
- 비동기 시나리오 처리
- 에러 핸들링

Effect는 이러한 한점을 해결하기 위해 만들어짐

Effect type을 사용하면 코드가 실행될 잠재적인 종속성을 표현할 수 있을 뿐 아니라 오류를 명시적으로 추적할 수 있다.

```tsx
type Effect<Success, Error, Requirements> = (
  context: Context<Requirements>
) => Error | Success
```

- Success
    - effect의 성공값
    - void: effect가 유용한 정보를 생성하지 않음
    - never: 영원히 (또는 실패할 때까지) 실행됨
- Error
    - 실행 중에 발생할 수 있는 모든 오류
    - never: effect가 실패할 수 없음
- Requirements
    - 실행할 effect에 필요한 컨텍스트 데이터

```tsx
const divide = (a: number, b: number) => {
  if (b === 0) {
    throw new Error("Cannot divide by zero");
  }
  return a / b;
};
```

 타입이 다음과 같이 추론됨

![image](https://github.com/user-attachments/assets/65cda836-d6bd-4952-b918-88a31e8ac5e4)


```tsx
import { Effect } from "effect"
 
const divide = (a: number, b: number): Effect.Effect<number, Error, never> =>
  b === 0
    ? Effect.fail(new Error("Cannot divide by zero"))
    : Effect.succeed(a / b)
```

- Success: number
- Error: Error
- Requirements: never

---

```tsx
const getData = () => {
  const response = await fetch("fetch someething from a random API");
  const parseResponse = await response.json();
  return dataSchema.parse(parseResponse);
};
```

> 각각의 라인에서 에러가 발생한다면?
> 

```tsx
import { Effect, pipe } from "effect";

const getData = (): Effect.Effect<never, Error, Data> => {
  return pipe(
    Effect.tryPromise({
      try: () => fetch("fetch something from a random API"),
      catch: () => new Error("Fetch returned an error"),
    }),

    Effect.flatMap((res) =>
      Effect.tryPromise({
        try: () => res.json(),
        catch: () => new Error("JSON parse cant be trusted also😭"),
      }),
    ),

    Effect.flatMap((json) =>
      Effect.try({
        try: () => dataSchema.parse(json),
        catch: () => new Error("This error is from the data schema"),
      }),
    ),
  );
```

- 이렇게 하면 getData 함수가 실행될 때 어떤 작업이 실패했는지, 왜 실패했는지 구체적으로 알 수 있다.
- 물론 위의 솔루션은 try...catch 블록을 사용하여 전체 함수를 래핑하고 예외를 던지는 것보다 더 장황한 방식이라는 것은 인정
    - 그럼에도 불구하고 Effect를 사용하면 각 오류가 구체적으로 처리되므로 코드를 더 쉽게 디버깅할 수 있다.

## Running Effects

### **`runSync`**

Effect를 동기적으로 실행하는데 사용

### **`runSyncExit`**

Effect를 동기적으로 실행하는데 사용되며, 결과를 Exit로 반환 (워크플로 실행 결과를 설명하는데 사용되는 데이터 유형)

### **`runPromise`**

Effect.runPromise 함수는 이펙트를 실행하고 그 결과를 프로미스로 가져오는 데 사용됩니다.

### **`runPromiseExit`**

Effect.runPromiseExit 함수는 Effect를 실행하고 그 결과를 Exit(Effect 워크플로 실행 결과를 설명하는 데 사용되는 데이터 유형)로 리졸브되는 Promise로 가져오는 데 사용됩니다.

## 파이프라인 구성

### pipe

읽기 쉽고 순차적인 방식으로 함수를 구성할 수 있는 유틸리티

여러 함수를 연결하여 복잡한 변환을 구축

```tsx
import { pipe } from "effect"
 
// Define simple arithmetic operations
const increment = (x: number) => x + 1
const double = (x: number) => x * 2
const subtractTen = (x: number) => x - 10
 
// Sequentially apply these operations using `pipe`
const result = pipe(5, increment, double, subtractTen)
 
console.log(result) // Output: 2
```

### 함수 vs 메서드

Effect 생태계에서 라이브러리는 메서드 보다는 함수를 노출하는 경우가 많다. 이러한 디자인 패턴은 트리셰이킹과 확장성이라는 두 가지 이유에서 중요함

- 트리셰이킹
    - 번들링 프로세스 중 사용하지 않는 코드를 제거
    - 함수는 트리셰이킹되지만 메서드는 그렇지 않다.
    - effect 생태계에서 함수를 사용하면 애플리케이션에서 실제로 가져와서 사용하는 함수만 최종 번들 코드에 포함됨
    - 사용하지 않는 함수는 자동으로 제거되므로 번들 크기가 작아지고 성능이 향상됨
    - 반면에 메서드는 객체나 프로포타입에 붙어 트리셰이킹되지 않는다. 메서드의 하위집합만 사용하더라도 객체 또는 프로토타입과 관련한 모든 메서드가 번들에 포함되므로 불필요한 코드가 많이 포함됨
- 확장성
    - 메서드를 사용하면 기존 api의 기능을 확장하려면 객체의 프로토타입을 수정해야 하는 경우가 많은데, 이는 복잡하고 오류가 발생하기 쉽다.

## 에러 처리

### **`die` / `dieMessage`**

- die : 지정된 오류를 던지는 effect 를 반환
    
    ```tsx
    /Users/jungsoohyun/Documents/PROJECTS/effect-node/src/divide_die.ts:4
        ? Effect.die(new Error("Cannot divide by zero"))
                     ^
    Error: Cannot divide by zero
        at divide (/Users/jungsoohyun/Documents/PROJECTS/effect-node/src/divide_die.ts:4:18)
        at Object.<anonymous> (/Users/jungsoohyun/Documents/PROJECTS/effect-node/src/divide_die.ts:6:16)
        at Module._compile (node:internal/modules/cjs/loader:1376:14)
        at Module.m._compile (/Users/jungsoohyun/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/index.ts:1618:23)
        at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
        at Object.require.extensions.<computed> [as .ts] (/Users/jungsoohyun/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/index.ts:1621:12)
        at Module.load (node:internal/modules/cjs/loader:1207:32)
        at Function.Module._load (node:internal/modules/cjs/loader:1023:12)
        at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
        at phase4 (/Users/jungsoohyun/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/bin.ts:649:14) {
      name: '(FiberFailure) Error',
      [Symbol(effect/Runtime/FiberFailure)]: Symbol(effect/Runtime/FiberFailure),
      [Symbol(effect/Runtime/FiberFailure/Cause)]: {
        _tag: 'Die',
        defect: Error: Cannot divide by zero
            at divide (/Users/jungsoohyun/Documents/PROJECTS/effect-node/src/divide_die.ts:4:18)
            at Object.<anonymous> (/Users/jungsoohyun/Documents/PROJECTS/effect-node/src/divide_die.ts:6:16)
            at Module._compile (node:internal/modules/cjs/loader:1376:14)
            at Module.m._compile (/Users/jungsoohyun/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/index.ts:1618:23)
            at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
            at Object.require.extensions.<computed> [as .ts] (/Users/jungsoohyun/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/index.ts:1621:12)
            at Module.load (node:internal/modules/cjs/loader:1207:32)
            at Function.Module._load (node:internal/modules/cjs/loader:1023:12)
            at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
            at phase4 (/Users/jungsoohyun/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/bin.ts:649:14)
      }
    }
    ```
    
- dieMessage 지정된 텍스트 메시지와 함께 런타임 에러를 던짐
    
    ```tsx
    RuntimeException: Cannot divide by zero
        at /Users/jungsoohyun/Documents/PROJECTS/effect-node/node_modules/effect/src/internal/core.ts:707:41 {
      name: '(FiberFailure) RuntimeException',
      [Symbol(effect/Runtime/FiberFailure)]: Symbol(effect/Runtime/FiberFailure),
      [Symbol(effect/Runtime/FiberFailure/Cause)]: {
        _tag: 'Die',
        defect: RuntimeException: Cannot divide by zero
            at EffectPrimitive.effect_instruction_i0 (/Users/jungsoohyun/Documents/PROJECTS/effect-node/node_modules/effect/src/internal/core.ts:707:41)
            at body (/Users/jungsoohyun/Documents/PROJECTS/effect-node/node_modules/effect/src/internal/fiberRuntime.ts:1109:41)
            at Object.effect_internal_function (/Users/jungsoohyun/Documents/PROJECTS/effect-node/node_modules/effect/src/Utils.ts:794:14)
            at /Users/jungsoohyun/Documents/PROJECTS/effect-node/node_modules/effect/src/Utils.ts:798:22
            at FiberRuntime.Sync (/Users/jungsoohyun/Documents/PROJECTS/effect-node/node_modules/effect/src/internal/fiberRuntime.ts:1109:31)
            at f (/Users/jungsoohyun/Documents/PROJECTS/effect-node/node_modules/effect/src/internal/fiberRuntime.ts:1343:53)
            at Object.context (/Users/jungsoohyun/Documents/PROJECTS/effect-node/node_modules/effect/src/internal/tracer.ts:93:19)
            at FiberRuntime.runLoop (/Users/jungsoohyun/Documents/PROJECTS/effect-node/node_modules/effect/src/internal/fiberRuntime.ts:1333:28)
            at FiberRuntime.evaluateEffect (/Users/jungsoohyun/Documents/PROJECTS/effect-node/node_modules/effect/src/internal/fiberRuntime.ts:893:27)
            at FiberRuntime.start (/Users/jungsoohyun/Documents/PROJECTS/effect-node/node_modules/effect/src/internal/fiberRuntime.ts:947:14) {
          _tag: 'RuntimeException'
        }
      }
    }
    ```
    

## Fallback

### `orElse`

- 하나의 effect를 시도하고 실패하면, 다른 effect를 시도할 수 있다.

### `orElseFail`/ `orElseSucceed`

이 두 연산자는 원래의 실패를 상수 성공 또는 실패 값으로 대체하여 수정합니다.

- orElseFail: 항상 원래의 실패를 새 실패로 대체
- orElseSucceed: 항상 원래의 실패를 성공 값으로 대체하므로, 결과 effect는 실패할 수 없다.

## Matching

성공/실패 케이스를 동시에 처리할 수 있도록 함

### `match`

success, failure 케이스에 대한 핸들러를 제공

### **`matchCause` / `matchCauseEffect`**

에러 발생 시 에러의 cause에 액세스하는 데 유용

이를 통해 다양한 장애 원인을 개별적으로 처리하고 적절한 조치를 취할 수 있다.

## Retrying

소프트웨어 개발 중에는 네트워크 문제, 리소스 사용불가 등 다양한 요인으로 작업이 일시적으로 실패하는 상황이 발생함.

이러한 경우 자동으로 재시도할 수 있도록 함

### `retry`

재시도할 effect와 재시도 전략을 인자로 넘긴다.

### `retry n times`

재시도 전략을 단순하게 축약하여 표현

### `retryOrElse`

오류 발생 시 폴백 전략을 정의할 수 있음

## Timing out

작업이 완료될 때까지 기다릴 수 있는 시간을 제한하고 싶을 때가 있다

### `timeout`

## Concurrency

독립적으로 스케줄링할 수 있는 경량 실행 스레드인 **fiber**를 사용하여 동시 프로그래밍을 위한 기능을 제공

### zip을 사용하여 순차적 실행

```tsx
import { Effect, Console } from "effect"
 
const task1 = Effect.delay(Console.log("task1"), "1 second")
const task2 = Effect.delay(Console.log("task2"), "2 seconds")
 
const program = Effect.zip(task1, task2)
 
Effect.runPromise(Effect.timed(program)).then(([duration]) =>
  console.log(String(duration))
)
/*
Output:
task1
task2
Duration(3s 5ms 369875ns)
*/
```

### zip을 사용하여 두 개의 작업을 동시에 실행

```tsx
import { Effect, Console } from "effect"
 
const task1 = Effect.delay(Console.log("task1"), "1 second")
const task2 = Effect.delay(Console.log("task2"), "2 seconds")
 
const program = Effect.zip(task1, task2, { concurrent: true })
 
Effect.runPromise(Effect.timed(program)).then(([duration]) =>
  console.log(String(duration))
)
/*
Output:
task1
task2
Duration(2s 8ms 179666ns)
*/
```

### race

여러 effect를 동시에 레이스하고, 성공적으로 완료된 첫번째 Effect의 효과를 반환

```tsx
import { Effect } from "effect"
 
const task1 = Effect.delay(Effect.fail("task1"), "1 second")
const task2 = Effect.delay(Effect.succeed("task2"), "2 seconds")
 
const program = Effect.race(task1, task2)
 
Effect.runPromise(program).then(console.log)
/*
Output:
task2
*/
```

## RxJS vs Effect

|  | Effect | RxJS |
| --- | --- | --- |
| 프로그래밍 패러다임 | 함수형 프로그래밍
(Functional Programming) | 반응형 프로그래밍
(Reactive Programming) |
| 주요 기능 | Effect, fibers | Observables |
| 에러 핸들링 | O | O |
| 장점 | - 타입 안정성
- 강력한 에러 핸들링
- 테스트  | - Composability (https://v3-docs.vuejs-korea.org/guide/reusability/composables.html#what-is-a-composable)
- 상태 관리
- 에러 핸들링 |
| 단점 | - 러닝 커브
- 장황한 코드 | - 데이터 불변성 필요
- 테스트 복잡 |
| 커뮤니티, 생태계 | 성장세 | 1군 |

https://www.youtube.com/shorts/Yhi2NGYVh6w
